[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$7h3j/L.3FuKcs7Y2xrj3Hg$kKc49H/6rnjJtiRqrBHkVmHDLwdVDyodC8E29KwtSxzTtNBPPw0oj2o8QO3Td4oZmPfPmLMNej6ER7n08vASpg
db_host = mydb
db_port = 5432
db_user = odoo
db_password = myodoo

